### ISSUE TITLE
Authorize `arcus-automation` user to use the Arcus DevOps templates

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/testing-framework#20]
**Is your feature request related to a problem? Please describe.**
The YAML build would require some DevOps templates we have created [previously](https://github.com/arcus-azure/azure-devops-templates).

**Describe the solution you'd like**
The `arcus-automation` user has to be authorized as a GitHub [Service Connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml).

**Comment by tomkerkhove** [comment]
Our `invictus-integration` connection should work fine like this:
```yaml
resources:
  repositories:
    - repository: templates
      type: github
      name: arcus-azure/azure-devops-templates
      endpoint: invictus-integration
```
